name: "dbt_estudo_sql_server"
version: "1.0.0"
config-version: 2

profile: "dbt_estudo_sql_server"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_estudo_sql_server:
    stage:
      +materialized: ephemeral

    trusted:
      +schema: trusted
      +materialized: table

    refined:
      +schema: refined
      +materialized: table

seeds:
  +schema: seeds